# Server
server.port=8082

# Application
spring.application.name=chunking-engine

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/chunking_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
