# Server
server.port=8081

# Application
spring.application.name=firehose

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=firehose-group
spring.kafka.consumer.auto-offset-reset=earliest

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/firehose_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200
